user www-data;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # HTTPS server for domain
    server {
        listen 443 ssl;
        server_name stitovsk.42.fr;

        ssl_certificate /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
		location ~ \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }

    # HTTP redirect for domain
    server {
        listen 80;
        server_name stitovsk.42.fr;
        return 301 https://$host$request_uri;
    }

    # HTTP redirect for localhost
    server {
        listen 80 default_server;
        server_name localhost;
        return 301 https://stitovsk.42.fr$request_uri;
    }
}